{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  {{- if not (empty .Values.emqxConfig.EMQX_DASHBOARD__DEFAULT_USERNAME) }}
  username: admin
  {{- else }}
  username: {{ .Values.emqxConfig.EMQX_DASHBOARD__DEFAULT_USERNAME }}
  {{- end }}
  {{- if not (empty .Values.emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD) }}
  password: public
  {{- else }}
  password: {{ .Values.emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD}}
  {{- end }}
{{- end }}
